import polars as pl
from evaluate_rule import evaluate_rule

from da_hf5_dz.config import OLD_DZ_RULE, filepath_shared_folder
from da_hf5_dz.configs.plotting.plotting import setup_plotting

setup_plotting()

rules = [
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "dist_1_end_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER"
    ],
    [
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "eq_BE_NAME",
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER"
    ],
    [
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER"
    ],
    [
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "dist_1_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_end_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "eq_end_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "eq_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_BETR_POSITION",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "dist_1_end_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "dist_2_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_end_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_DocClass",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_1_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_2_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_PKV_PK",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_pos_len"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_end_date",
      "eq_pos_len"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_end_date"
    ],
    [
      "eq_BE_NAME",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_TAB_BETR_POSITION",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "eq_pos_len"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "dist_2_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_2_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "eq_pos_len"
    ],
    [
      "eq_DocClass",
      "overlap_0_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "overlap_0.5_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "eq_pos_len"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "dist_2_clean_BEL_BETR_RECHNUNG",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "dist_1_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_end_date",
      "eq_pos_len"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_DocClass",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_DocClass",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_DAT_VERORDNUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_DocClass",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_PKV_PK",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG",
      "dist_2_end_date",
      "dist_2_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_DAT_LSTG_VON",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_1_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "eq_end_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len",
      "dist_1_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "eq_DocClass",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_clean_BEL_DAT_VERORDNUNG"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.99_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len"
    ],
    [
      "eq_PKV_PK",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "eq_pos_len",
      "dist_1_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_DocClass",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "eq_start_date"
    ],
    [
      "eq_BE_NAME",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "overlap_0_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "eq_start_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_end_date",
      "dist_2_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "eq_pos_len",
      "dist_1_start_date"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_1_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_pos_len",
      "dist_1_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_2_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_1_end_date"
    ],
    [
      "eq_DocClass",
      "overlap_0.5_TAB_BETR_POSITION",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_end_date",
      "eq_pos_len"
    ],
    [
      "dist_1_clean_BEL_BETR_RECHNUNG",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_PKV_PK",
      "overlap_0.5_TAB_DAT_LSTG_VON",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "eq_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "dist_2_end_date",
      "eq_pos_len"
    ],
    [
      "eq_TAB_BETR_POSITION",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "dist_1_end_date",
      "eq_pos_len"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "overlap_0_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_DocClass",
      "eq_TAB_BETR_POSITION",
      "dist_1_end_date"
    ],
    [
      "eq_DocClass",
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "eq_pos_len",
      "dist_1_start_date"
    ],
    [
      "eq_BE_NAME",
      "eq_DocClass",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "dist_1_start_date"
    ],
    [
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date",
      "eq_pos_len"
    ],
    [
      "eq_BE_STRASSE_NR",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_2_end_date"
    ],
    [
      "eq_PKV_PK",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "dist_2_end_date",
      "eq_pos_len"
    ],
    [
      "eq_DocClass",
      "eq_clean_BEL_BETR_RECHNUNG",
      "dist_1_end_date",
      "dist_1_start_date"
    ],
    [
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_DIAG_ZIFFER",
      "overlap_0_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_PKV_PK",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_DocClass",
      "eq_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0.5_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "eq_DocClass",
      "overlap_0.5_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER"
    ],
    [
      "overlap_0_TAB_BETR_POSITION",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG"
    ],
    [
      "eq_DocClass",
      "eq_PKV_PK",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_pos_len"
    ],
    [
      "eq_DocClass",
      "eq_PKV_PK",
      "eq_clean_BEL_BETR_RECHNUNG",
      "eq_clean_BEL_DAT_AUSSTELLUNG"
    ],
    [
      "eq_clean_BEL_DAT_VERORDNUNG",
      "eq_end_date",
      "eq_start_date"
    ],
    [
      "eq_PKV_PK",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "eq_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_BE_STRASSE_NR",
      "eq_clean_BEL_DAT_AUSSTELLUNG",
      "overlap_0_clean_TAB_GEBUEHZIFFER",
      "dist_1_end_date",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "eq_PKV_PK",
      "dist_2_end_date",
      "eq_pos_len",
      "eq_start_date"
    ],
    [
      "eq_DocClass",
      "prop_0.95_clean_BEL_BETR_RECHNUNG",
      "eq_end_date"
    ],
    [
      "eq_DocClass",
      "dist_2_clean_BEL_BETR_RECHNUNG",
      "dist_2_end_date",
      "eq_start_date"
    ]
]

filter_expression = (
    ~OLD_DZ_RULE
    & (~pl.col("lar").str.starts_with("3") | ~pl.col("lar__2").str.starts_with("3"))
    & pl.col("lar").ne("141")
)

data_path = (
    filepath_shared_folder
    / "dz/labelling/full_data_sets"
    / "25_12_25_2y_historic_all_labels_without_unclear__27_04_2026_.parquet"
)

result = evaluate_rule(
    greedy_rules=rules,
    final_rules=rules,
    filter_expression=filter_expression,
    label_col="dz_interesting",
    data_path=data_path,
    review_cost=5.3,
    min_reimbursement_threshold=0.0,
)

result["November_2025__October_2025"]["greedy"]["pr_value"].savefig(
    "November_2025__October_2025_greedy_pr_value.png", bbox_inches="tight"
)
result["November_2025__2_years_historic"]["greedy_estimated"][
    "expected_savings"
].savefig("November_2025__2_years_historic_greedy_pr_value.png", bbox_inches="tight")

# Print savings summary
for window_name, comp_dict in result.items():
    for comp_name, d in comp_dict.items():
        print(f"\n=== {window_name} / {comp_name} ===")
        print(f"  all_pos savings: {d['savings_all_pos']}")
        print(f"  tp savings:      {d['savings_tp']}")
        print(f"  in_stack:        {d['in_stack_stats']}")
        print(f"  out_of_stack:    {d['out_of_stack_stats']}")
        d["pr_value"].savefig(
            f"{window_name}_{comp_name}_pr_value.png", bbox_inches="tight"
        )
        d["lar_heatmap"].savefig(
            f"{window_name}_{comp_name}_lar_heatmap.png", bbox_inches="tight"
        )
        d["time_difference"].savefig(
            f"{window_name}_{comp_name}_time_diff.png", bbox_inches="tight"
        )
